apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: talos-proxmox-autoscaler-leaderelection
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/name: talos-proxmox-autoscaler
    app.kubernetes.io/component: autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: talos-proxmox-autoscaler-leaderelection
subjects:
  - kind: ServiceAccount
    name: talos-proxmox-autoscaler
    namespace: autoscaler-system
