apiVersion: v1
kind: ServiceAccount
metadata:
  name: talos-proxmox-autoscaler
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/name: talos-proxmox-autoscaler
    app.kubernetes.io/component: autoscaler
