apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/name: talos-proxmox-autoscaler
    app.kubernetes.io/component: autoscaler
data:
  cluster_name: "talos"
  min_workers: "1"
  max_workers: "20"
  min_cpu: "2"
  max_cpu: "8"
  min_memory_gib: "4"
  max_memory_gib: "16"
  disk_gib: "100"
  storage_pool: "local-lvm"
  network_bridge: "vmbr0"
  mac_address: ""
  serial: ""
  proxmox_api_url: "https://pve.example.com:8006"
  proxmox_insecure: "true"
  base_vmid: "2000"
  tags: "autoscaler,worker"
  vlan_id: "0"
  pci_devices: '[{"id":"0000:01:00.0","pcie":true,"gpu":true}]'
  worker_nodes: '[{"name":"worker-vm"}]'
  worker_gpu_nodes: '[{"type":"p4","nodes":["worker-vm-gpu"],"pci_devices":[{"id":"0000:01:00.0","pcie":true,"gpu":true}]}]'
