apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/name: talos-proxmox-autoscaler
    app.kubernetes.io/component: autoscaler
data:
  cluster_name: "talos"
  min_workers: "1"
  max_workers: "20"
  min_cpu: "2"
  max_cpu: "8"
  min_memory_gib: "4"
  max_memory_gib: "16"
  disk_gib: "100"
  storage_pool: "local-lvm"
  network_bridge: "vmbr0"
  mac_address: ""
  serial: ""
  proxmox_api_url: "https://pve.example.com:8006"
  proxmox_insecure: "true"
  base_vmid: "2000"
  tags: "autoscaler,worker"
  vlan_id: "0"
  base_gpu_vmid: "3000"
  worker_prefix: "worker-vm"
  gpu_prefix: "worker-vm-gpu"
  worker_nodes: '[{"name":"worker-vm"}]'
  worker_gpu_nodes: '[{"type":"tesla-p4","nodes":["pve1","pve2"],"pci_devices":[{"id":"0000:01:00.0","pcie":true,"gpu":true}]},{"type":"tesla-p40","nodes":["pve3"],"pci_devices":[{"id":"0000:41:00.0","pcie":true,"gpu":true}]}]'
