apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: autoscaler-system
data:
  cluster_name: "talos"
  min_workers: "1"
  max_workers: "10"
  vcpu: "4"
  memory_gib: "8"
  disk_gib: "100"
  storage_pool: "local-lvm"
  network_bridge: "vmbr0"
  mac_address: ""
  serial: ""
  proxmox_api_url: "https://pve.example.com:8006"
  proxmox_node: "pve"
  proxmox_insecure: "true"
  base_vmid: "2000"
  base_gpu_vmid: "3000"
  worker_prefix: "worker-vm"
  gpu_prefix: "worker-vm-gpu"
  worker_nodes: '[{"name":"worker-vm"}]'
  worker_gpu_nodes: '[{"type":"tesla-p4","nodes":["pve1","pve2"],"pci_devices":[{"id":"0000:01:00.0","pcie":true,"gpu":true}]},{"type":"tesla-p40","nodes":["pve3"],"pci_devices":[{"id":"0000:41:00.0","pcie":true,"gpu":true}]}]'
