apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: talos-worker-scaler
  namespace: autoscaler-system
spec:
  scaleTargetRef:
    name: talos-proxmox-autoscaler
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: talos-proxmox-autoscaler.autoscaler-system:8080
        safeHpaMinimum: "0"
